export const songs = [
  {
    id: 1,
    title: "Kesariya",
    artist: "Arijit Singh",
    genre: "Romantic",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    image: "https://picsum.photos/400/400?random=1",
  },
  {
    id: 2,
    title: "Believer",
    artist: "Imagine Dragons",
    genre: "Pop",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    image: "https://picsum.photos/400/400?random=2",
  },
  {
    id: 3,
    title: "Perfect",
    artist: "Ed Sheeran",
    genre: "Romantic",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    image: "https://picsum.photos/400/400?random=3",
  },
  {
    id: 4,
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    image: "https://picsum.photos/400/400?random=4",
  },
  {
    id: 5,
    title: "Levitating",
    artist: "Dua Lipa",
    genre: "Dance",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    image: "https://picsum.photos/400/400?random=5",
  },
  {
    id: 6,
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "Pop",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    image: "https://picsum.photos/400/400?random=6",
  },
  {
    id: 7,
    title: "Senorita",
    artist: "Shawn Mendes",
    genre: "Romantic",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    image: "https://picsum.photos/400/400?random=7",
  },
  {
    id: 8,
    title: "Bad Guy",
    artist: "Billie Eilish",
    genre: "Alternative",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    image: "https://picsum.photos/400/400?random=8",
  },
  {
    id: 9,
    title: "Heat Waves",
    artist: "Glass Animals",
    genre: "Indie",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    image: "https://picsum.photos/400/400?random=9",
  },
  {
    id: 10,
    title: "On My Way",
    artist: "Alan Walker",
    genre: "EDM",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    image: "https://picsum.photos/400/400?random=10",
  },
];
